### ISSUE TITLE
Could we access to the training code?

### ISSUE THREAD

**Issue by seamanj** [Unibas3D/Upper-Limb-Segmentation#2]
Very fantanstic work. really want to reproduce the results. Was wondering whether we could access to training code? already sent an email for dataset access. 

Many thanks

**Comment by gruossomonica** [comment]
Hi,
thanks for your interest!
Since our networks were based on DeepLabv3+, we used the code available on the [DeepLab GitHub repo](https://github.com/tensorflow/models/tree/master/research/deeplab). Training details are indicated in our papers, in particular, "Solid and Effective Upper Limb Segmentation in Egocentric Vision" (project page [here](http://graphics.unibas.it/www/EgoUpperLimbSeg/index.md.html)).
